# Generated by Django 5.2.8 on 2025-11-15 07:42

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Required. A valid email address.', max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number in international format', max_length=128, null=True, region=None, verbose_name='phone number')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (max 5MB, formats: jpg, png, gif, webp)', null=True, upload_to='avatars/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='avatar')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their phone number.', verbose_name='phone verified')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('bio', models.TextField(blank=True, help_text='Brief description about yourself (max 500 characters)', max_length=500, verbose_name='biography')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='occupation')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='company')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('id_proof_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('other', 'Other')], max_length=50, verbose_name='ID proof type')),
                ('id_proof_number', models.CharField(blank=True, max_length=100, verbose_name='ID proof number')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='emergency contact name')),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='emergency contact phone')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences stored as JSON', verbose_name='preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('other', 'Other')], default='home', max_length=20, verbose_name='address type')),
                ('street_address_1', models.CharField(max_length=255, verbose_name='street address line 1')),
                ('street_address_2', models.CharField(blank=True, max_length=255, verbose_name='street address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state_province', models.CharField(max_length=100, verbose_name='state/province')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='country')),
                ('is_default', models.BooleanField(default=False, help_text='Designates if this is the default address for this user.', verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('phone', 'Phone Verification'), ('email', 'Email Verification'), ('two_factor', 'Two-Factor Authentication')], default='phone', max_length=20, verbose_name='verification type')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number being verified', max_length=128, null=True, region=None, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, help_text='Email address being verified', max_length=254, verbose_name='email address')),
                ('otp_code', models.CharField(blank=True, help_text='One-time password code', max_length=10, verbose_name='OTP code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of verification attempts', verbose_name='verification attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum allowed verification attempts', verbose_name='maximum attempts')),
                ('expires_at', models.DateTimeField(help_text='When this verification code expires', verbose_name='expires at')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the verification was completed', null=True, verbose_name='verified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'verification',
                'verbose_name_plural': 'verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='users_addre_user_id_194804_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['user', 'status'], name='users_verif_user_id_e9033f_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['phone_number', 'status'], name='users_verif_phone_n_20dd31_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['expires_at'], name='users_verif_expires_f502b2_idx'),
        ),
    ]
